name: ci
on:
  push:
    branches:
      - main
  pull_request:
jobs:
  ci:
    name: CI
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: "yarn"
      - name: Install
        run: yarn install --immutable
      - name: Lint
        run: yarn run lint
